
Epoch 0
  0%|                                                                                       | 0/704 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "training.py", line 155, in <module>
    main()
  File "training.py", line 146, in main
    trainer.fit(train_loader, val_loader)
  File "training.py", line 77, in fit
    self.train_n_iters(train_loader)
  File "training.py", line 36, in train_n_iters
    loss, x_hats = self.model(images, labels)
  File "/home/max/.pyenv/versions/dgm_project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/.pyenv/versions/dgm_project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/uni/dgm_project/modules/cvae.py", line 70, in forward
    mu, logvar = self.encode(x, labels)
  File "/home/max/uni/dgm_project/modules/cvae.py", line 52, in encode
    mu = self.fc_mu(x)
  File "/home/max/.pyenv/versions/dgm_project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/.pyenv/versions/dgm_project/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/.pyenv/versions/dgm_project/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x784 and 3136x32)